{% set name = "tapse" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url:  https://github.com/schinavro/taps/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4daf7e66312c4047fd0e5ce94e9b17268ea667d995fbe608a1ed367aec86b7f7
# curl -sL https://github.com/schinavro/taps/archive/refs/tags/v0.1.tar.gz | openssl sha256

build:
  number: 0
  skip: True  # [not linux]
  # script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python <=3.7
  run:
    - python <=3.7
    - ase

about:
  home: https://github.com/schinavro/taps
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Totally Accurate Pathway Simulator (TAPS)"
  doc_url: https://taps0313.readthedocs.io
  dev_url: https://github.com/schinavro/taps

extra:
  recipe-maintainers:
    - schinavro
